version: "3.9"

services:
  app:
    build:
      context: ./docker/php
    container_name: shop-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - shop-network
    depends_on:
      - db
      - redis
      - meilisearch

  nginx:
    build:
      context: ./docker/nginx
    container_name: shop-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shop-network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: shop-db
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
      POSTGRES_DB: shopdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shop-network

  redis:
    image: redis:7
    container_name: shop-redis
    ports:
      - "6379:6379"
    networks:
      - shop-network

  meilisearch:
    image: getmeili/meilisearch:v1.2
    container_name: shop-meilisearch
    environment:
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/data.ms
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge

volumes:
  pgdata:
  meili_data:
